branches:
  only:
    - master

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env: COMPONENT=server
    - os: osx
      osx_image: xcode9
      env: COMPONENT=server
    - os: osx
      osx_image: xcode9
      env: COMPONENT=iOS

before_install:
  - git clone -b master https://github.com/IBM-Swift/Package-Builder.git ToDoServer/Package-Builder

script:
  - if [[ "$COMPONENT" == "server" ]]; then cd $TRAVIS_BUILD_DIR/ToDoServer && ./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR; fi
  - if [[ "$COMPONENT" == "iOS" ]]; then cd $TRAVIS_BUILD_DIR/KituraiOS; xcodebuild -workspace iOSKituraKitSample.xcworkspace/ -scheme iOSKituraKitSample -sdk iphonesimulator11.0 ONLY_ACTIVE_ARCH=NO -quiet; fi
